itu-auv/auv-software

auv_bringup/CMakeLists.txt, auv_bringup/launch/inc/imu/start_xsens_driver.launch.xml, auv_bringup/package.xml, third_party.repos
Can be tested with `roslaunch auv_bringup start_xsens_driver.launch.xml port:=/dev/auv_imu`
=> Add xsens mti imu driver

auv_teleop/CMakeLists.txt, auv_teleop/README.md, auv_teleop/launch/start_teleop.launch, auv_teleop/package.xml, auv_teleop/scripts/joy_manager.py
=> added simple joystick node

auv_teleop/scripts/joy_manager.py
Added publishing /taluy/enable message in teleop node.
=> add enable message pub to joy manager

auv_control/auv_control/CMakeLists.txt, auv_control/auv_control/cfg/Controller.cfg, auv_control/auv_control/include/auv_control/controller_ros.h, auv_control/auv_control/launch/start.launch
Added Dynamic Reconfigure to AUV Control
=> Added Dynamic Reconfigure to AUV Control

auv_control/auv_control/launch/start.launch, auv_control/auv_control/scripts/depth_controller_node.py, auv_localization/launch/start.launch, auv_localization/scripts/dvl_odometry_node.py
DVL odometry updated, added cmd vel fallback.
=> DVL Odometry update

auv_control/auv_control/CMakeLists.txt, auv_control/auv_control/launch/start.launch, auv_control/auv_control/scripts/battery_monitor_node.py
=> added battery monitor node

auv_control/auv_control/CMakeLists.txt, auv_control/auv_control/scripts/bin_transform_publisher.py
=> WIP added bin transform publisher

auv_navigation/auv_mapping/scripts/object_map_tf_server.py
fixed data racing at object map tf server
=> fixed data racing at object map tf server

auv_control/auv_control/scripts/battery_monitor_node.py
=> fix battery monitor node

auv_sim/auv_sim_bringup/launch/start_gazebo.launch, auv_sim/auv_sim_description/auv_sim_description/worlds/pool.world
=> Adjust robot and buoy positions in simulation

auv_bringup/launch/inc/logging.launch.xml, auv_bringup/launch/start.launch, auv_sim/auv_sim_bringup/launch/start_gazebo.launch
This PR is updated version of this PR (#117) . Because of the long journey that we cannot fix the issue in the logging functionality, I just added the arguments that open or disable logging for preventing the huge mass of bag files from the dry tests.
=> feat: add logging configuration options to launch files

auv_control/auv_control/launch/start.launch, auv_control/auv_control/scripts/align_frame_controller.py, auv_navigation/auv_localization/launch/start.launch, auv_navigation/auv_localization/scripts/dvl_odometry_node.py, auv_navigation/auv_localization/scripts/imu_odometry_node.py, auv_navigation/auv_localization/scripts/pressure_odometry_node.py, auv_smach/launch/start.launch, auv_smach/scripts/main_state_machine.py, auv_smach/src/auv_smach/common.py, auv_smach/src/auv_smach/gate.py, auv_smach/src/auv_smach/initialize.py, auv_smach/src/auv_smach/red_buoy.py
Closes #142 
This PR addresses issues with absolute topic names and standardizes the naming conventions for services, topics, and parameters. These changes enhance code clarity and maintainability.
=> fix topic names

auv_smach/src/auv_smach/common.py
=> Remove out of place import at common.py

auv_navigation/auv_navigation/CMakeLists.txt, auv_navigation/auv_navigation/package.xml, auv_navigation/auv_navigation/scripts/follow_path_action_server.py, auv_navigation/auv_navigation/src/auv_navigation/path_utils.py
Reverts itu-auv/auv-software#163
=> Revert "Various refactoring to auv_navigation"

auv_navigation/auv_localization/config/sensor_calibration_data.yaml, auv_navigation/auv_localization/launch/start.launch, auv_navigation/auv_localization/scripts/pressure_odometry_node.py
Closes #70 
Closes #62 
This is an updated version of pr #62 . It was a hassle to rebase it since it was a long time ago. It also caused problems with odometry, so I thought it would be more accurate to get the orientation information directly from the IMU sensor.
=> Update pressure odometry

auv_navigation/auv_localization/scripts/imu_odometry_node.py
Closes #173 
- Created update_pose_covariance and update_twist_covariance helpers to insert the 3x3 orientation covariance from the IMU message into the 6x6 pose covariance matrix. We use the concept of _inserting a matrix to the chunk of a bigger matrix_ for elegancy:
```python
imu_angular_velocity_covariance_matrix = np.array(
imu_angular_velocity_covariance
).reshape(3, 3)
twist_cov[3:6, 3:6] = imu_angular_velocity_covariance_matrix
```
- The helper functions include a check about whether the incoming IMU orientation/angular velocity covariance data has the expected length of 9 elements before attempting to reshape it into a 3x3 matrix.
This correctly signals high uncertainty for these components, which is the best practice instead of leaving them at 0 (implying perfect certainty :D) …
=> Fix and improve covariance handling in `imu_odometry_node`

auv_navigation/auv_mapping/launch/start.launch, auv_navigation/auv_mapping/scripts/gate_trajectory_publisher.py, auv_smach/launch/start.launch, auv_smach/src/auv_smach/gate.py, auv_smach/src/auv_smach/initialize.py
=> Rename the service for gate trajectory control

auv_navigation/auv_mapping/config/gate_trajectory_publisher_params.yaml, auv_navigation/auv_mapping/scripts/gate_trajectory_publisher.py
=> Parallel Offset for Entrance and Exit frames

auv_navigation/auv_localization/scripts/imu_odometry_node.py
=>  Use the timestamp from the IMU message instead of now

auv_control/auv_control/scripts/align_frame_controller.py
=> fix(AFC): Add sleep duration after zeroing Twist

auv_navigation/auv_mapping/launch/start.launch, auv_vision/auv_detection/scripts/camera_detection_pose_estimator.py
=> Update altitude subscription to use odom_pressure 

auv_sim/auv_sim_bringup/launch/inc/start_image_processing.launch, auv_sim/auv_sim_bringup/launch/start_gazebo.launch
this is required because of #243
=> add image processing to sim

auv_control/auv_control/include/auv_control/controller_ros.h
`ros::Time::now()` -> `ros::Time(0)`
=> fix set_pose

auv_navigation/auv_mapping/src/realsense_filter.cpp
=> Refactor PointCloudFilterNode to use odometry 
